### ISSUE TITLE
ERROR: Exception on /admin/install/test_config [POST]

### ISSUE THREAD

**Issue by ma3252788** [abbeyokgo/PyOne#109]
2019-08-09 23:26:28,367 - ERROR: Exception on /admin/install/test_config [POST]
Traceback (most recent call last):
 File "/usr/lib/python2.7/site-packages/flask/app.py", line 2311, in wsgi_app
   response = self.full_dispatch_request()
 File "/usr/lib/python2.7/site-packages/flask/app.py", line 1835, in full_dispatch_request
   return self.finalize_request(rv)
 File "/usr/lib/python2.7/site-packages/flask/app.py", line 1850, in finalize_request
   response = self.make_response(rv)
 File "/usr/lib/python2.7/site-packages/flask/app.py", line 2001, in make_response
   reraise(TypeError, new_error, sys.exc_info()[2])
 File "/usr/lib/python2.7/site-packages/flask/app.py", line 1993, in make_response
   rv = self.response_class.force_type(rv, request.environ)
 File "/usr/lib/python2.7/site-packages/werkzeug/wrappers/base_response.py", line 269, in force_type
   response = BaseResponse(*_run_wsgi_app(response, environ))
 File "/usr/lib/python2.7/site-packages/werkzeug/test.py", line 1118, in run_wsgi_app
   app_rv = app(environ, start_response)
TypeError: 'dict' object is not callable
The view function did not return a valid response. The return type must be a string, tuple, Response instance, or WSGI callable, but it was a dict.

**Comment by Smthie** [comment]
解决了吗？同问。

**Comment by abbeyokgo** [comment]
请更新代码
