### ISSUE TITLE
无法读取部分目录下文件

### ISSUE THREAD

**Issue by x1184** [abbeyokgo/PyOne#11]
网页前台显示
**Internal Server Error**
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

----
服务器 `gunicorn` 直接启动后报错log:

```
[2018-11-11 13:54:58,968] ERROR in app: Exception on /xxx/xxx [GET]
Traceback (most recent call last):
  File "/usr/local/python27/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python27/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/python27/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/python27/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/python27/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/wwwroot/xxx/run.py", line 444, in show
    name=GetName(fileid)
  File "/www/wwwroot/xxx/function.py", line 58, in GetName
    rd.set(key,item['name'])
TypeError: 'NoneType' object has no attribute '__getitem__'
```

----
服务器`python function.py UpdateFile`命令可以正常执行
mongodb正常运行  netstat查看结果
```
tcp        0      0 127.0.0.1:27017             0.0.0.0:*                   LISTEN      2034/mongod         
tcp        0      0 127.0.0.1:50476             127.0.0.1:27017             TIME_WAIT   -                   
tcp        0      0 127.0.0.1:49900             127.0.0.1:27017             TIME_WAIT   -                   
unix  2      [ ACC ]     STREAM     LISTENING     3808300488 2034/mongod         /tmp/mongodb-27017.sock
```

**Comment by abbeyokgo** [comment]
请更新最新代码。
