### ISSUE TITLE
无法安装humanize //python官方停止支援Python2 Setup tool

### ISSUE THREAD

**Issue by e9965** [abbeyokgo/PyOne#138]

**Comment by e9965** [comment]
Complete output from command python setup.py egg_info:
    /usr/lib/python2.7/site-packages/pkg_resources/py2_warn.py:21: UserWarning: Setuptools will stop working on Python 2
    ************************************************************
    You are running Setuptools on Python 2, which is no longer
    supported and
    >>> SETUPTOOLS WILL STOP WORKING <<<
    in a subsequent release (no sooner than 2020-04-20).
    Please ensure you are installing
    Setuptools using pip 9.x or later or pin to `setuptools<45`
    in your environment.
    If you have done those things and are still encountering
    this message, please follow up at
    https://bit.ly/setuptools-py2-warning.
    ************************************************************
      sys.version_info < (3,) and warnings.warn(pre + "*" * 60 + msg + "*" * 60)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-MkY32c/humanize/setup.py", line 3, in <module>
        with open("README.md", encoding="UTF-8") as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-MkY32c/humanize/
