### ISSUE TITLE
执行pip install -r requirements.txt报错

### ISSUE THREAD

**Issue by ShaoPak** [abbeyokgo/PyOne#139]
Centos7

第一次是通过宝塔一键脚本安装，但是输入ip+端口打不开，端口也未生效，于是删了想着重新一步一步搭建，结果不知是怎么了，在下载源码后的执行pip install -r requirements.txt就报错了：
`    ERROR: Command errored out with exit status 1:
     command: /bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-W5EyUd/shelljob/setup.py'"'"'; __file__='"'"'/tmp/pip-install-W5EyUd/shelljob/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-uaLAWb
         cwd: /tmp/pip-install-W5EyUd/shelljob/
    Complete output (5 lines):
    Generating Description failed, press enter to process anyway, or kill to cancelTraceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-W5EyUd/shelljob/setup.py", line 15, in <module>
        input( 'Generating Description failed, press enter to process anyway, or kill to cancel' )
    EOFError: EOF when reading a line
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`
请问怎么解决呢

**Comment by lzkgbld** [comment]
这包需要其他依赖包支持，用pip3 install的时候，也会在这个包卡死，真不知道这怎么安装了。

**Comment by ShaoPak** [comment]
> 这包需要其他依赖包支持，用pip3 install的时候，也会在这个包卡死，真不知道这怎么安装了。

已经放弃了/苦笑

**Comment by Rom2333** [comment]
我也遇到了同样的问题 HostLoc的大佬说可以用debian安装PyOne
https://www.hostloc.com/thread-687260-1-1.html

**Comment by pudding1111** [comment]
同样的问题，无解啊

**Comment by pudding1111** [comment]
centos7 debian9我都试了，会报错ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-A0fEMq/shelljob/setup.py'"'"'; __file__='"'"'/tmp/pip-install-A0fEMq/shelljob/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-CsqJBS
         cwd: /tmp/pip-install-A0fEMq/shelljob/
    Complete output (5 lines):
    Generating Description failed, press enter to process anyway, or kill to cancelTraceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-A0fEMq/shelljob/setup.py", line 15, in <module>
        input( 'Generating Description failed, press enter to process anyway, or kill to cancel' )
    EOFError: EOF when reading a line
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by 1779729350** [comment]
shelljob 0.5.7版本可以安装，0.5.8报错，降级安装就行了

**Comment by pudding1111** [comment]
> shelljob 0.5.7版本可以安装，0.5.8报错，降级安装就行了

谢老哥，我在https://mintimate.cn/2019/11/01/Onedrive/的教程中找到解决方法，即更改requirements文件，centos和Debian都能成功安装
