### ISSUE TITLE
无法更新缓存

### ISSUE THREAD

**Issue by AlbertETA** [abbeyokgo/PyOne#2]
在缓存到期时也无法自动更新缓存，同时手动更新缓存时提示失败：

Traceback (most recent call last):
 File "/www/wwwroot/PyOne/function.py", line 676, in <module>
   eval(func+str(tuple(args)))
 File "<string>", line 1, in <module>
 File "/www/wwwroot/PyOne/function.py", line 159, in Dir
   parent_id=items.find_one({'name':p,'grandid':idx})['id']
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by AlbertETA** [comment]
经重装（完全重装，磁盘都初始化过了），发现问题依然存在，请撸主检查下function.py文件是不是有bug？？

**Comment by AlbertETA** [comment]
233333新版本成功能够更新文件了6666！！！不过似乎略有不顺，实践时不顺的情况描述在新issue里。
