### ISSUE TITLE
run.py和admin.py循环导入

### ISSUE THREAD

**Issue by comtnt** [abbeyokgo/PyOne#53]
直接python run.py会循环导入报ImportError
**error:**
```
(python2) C:\Users\Administrator\py_workspace\PyOne>C:/ProgramData/Anaconda3/envs/python2/python.exe c:/Users/Administrator/py_workspace/PyOne/run.py
Traceback (most recent call last):
  File "c:/Users/Administrator/py_workspace/PyOne/run.py", line 672, in <module>
    from admin import admin as admin_blueprint
  File "c:\Users\Administrator\py_workspace\PyOne\admin.py", line 8, in <module>
    from run import FetchData,path_list,GetName,CodeType,_remote_content,rd,has_item,AddResource
  File "c:\Users\Administrator\py_workspace\PyOne\run.py", line 672, in <module>
    from admin import admin as admin_blueprint
ImportError: cannot import name admin
```
**run.py 671line::**
```
######################注册应用
from admin import admin as admin_blueprint
app.register_blueprint(admin_blueprint)
```
**admin.py 8line:**
```
from run import FetchData,path_list,GetName,CodeType,_remote_content,rd,has_item,AddResource
```
**这样改下就不会循环导入了**
```
######################注册应用
def register_admin():
    from admin import admin as admin_blueprint
    app.register_blueprint(admin_blueprint)
...
################################################################################
#####################################启动#######################################
################################################################################
if __name__=='__main__':
    register_admin()
    app.run(port=58693,debug=True)
```

**Comment by abbeyokgo** [comment]
直接使用gunicorn不存在这种问题
