### ISSUE TITLE
后台-页面缓存-更新缓存 仍然无法更新。。。

### ISSUE THREAD

**Issue by AlbertETA** [abbeyokgo/PyOne#6]
感觉这个项目很棒，看图模式很实用，图片大小、位置放的刚刚好！！！
以下是目前遇到的一些问题：
环境：宝塔最新稳定版LNMP环境，全新状态（没错~我又重新初始化了磁盘。。）
版本：今天中午13:00下的最新版。
报错信息如下：
我的实际共享目录为“/share”。
若更新目录为“/”时：
Traceback (most recent call last):
 File "/www/wwwroot/PyOne/function.py", line 690, in <module>
   eval(func+'()')
 File "<string>", line 1, in <module>
 File "/www/wwwroot/PyOne/function.py", line 271, in UpdateFile
   Dir(share_path)
 File "/www/wwwroot/PyOne/function.py", line 163, in Dir
   parent_id=items.find_one({'name':p,'grandid':idx})['id']
TypeError: 'NoneType' object has no attribute '__getitem__'

若更新目录为“/share”时：
Traceback (most recent call last):
 File "/www/wwwroot/PyOne/function.py", line 688, in <module>
   eval(func+str(tuple(args)))
 File "<string>", line 1, in <module>
 File "/www/wwwroot/PyOne/function.py", line 163, in Dir
   parent_id=items.find_one({'name':p,'grandid':idx})['id']
TypeError: 'NoneType' object has no attribute '__getitem__'

老哥咱这得考虑下如何自动更新缓存呀，要不文件变更后在网页上并无变化（考虑过缓存延时后），目前感觉缓存得每次在网页后台（网址/admin。非终端）手动更新，而手动更新时就会遇到如上的报错。

**Comment by abbeyokgo** [comment]
留个联系方式，我调试一下

**Comment by AlbertETA** [comment]
可能是宝塔中的mongoDB出了问题，安装mongoDB状态不正常。正在检查该部分

**Comment by AlbertETA** [comment]
的确是宝塔面板安装mongoDB时出现了问题，需同时安装Memcached，并对mongoDB进行两三次卸载重装后才算能正常安装上。
