### ISSUE TITLE
mjj 前来报错

### ISSUE THREAD

**Issue by sky-sunny** [abbeyokgo/PyOne#62]
添加第二网盘时
2019-02-27 12:54:53,106 - INFO: get key:has_item$#$#$#$#A:/$#$#$#$#.password
2019-02-27 12:54:53,108 - INFO: get key:has_item$#$#$#$#A:/$#$#$#$#.password
2019-02-27 12:54:53,111 - INFO: get key:has_item$#$#$#$#/$#$#$#$#.password
2019-02-27 12:54:53,113 - INFO: get key:has_item$#$#$#$#A:/$#$#$#$#README.md
2019-02-27 12:54:53,115 - INFO: get key:has_item$#$#$#$#A:/$#$#$#$#readme.md
2019-02-27 12:54:53,118 - INFO: get key:has_item$#$#$#$#A:/$#$#$#$#readme.txt
2019-02-27 12:54:53,120 - INFO: get key:has_item$#$#$#$#A:/$#$#$#$#README.txt
2019-02-27 12:54:53,122 - INFO: get key:has_item$#$#$#$#A:/$#$#$#$#HEAD.md
2019-02-27 12:54:53,124 - INFO: get key:has_item$#$#$#$#A:/$#$#$#$#head.md
2019-02-27 12:54:53,126 - INFO: get key:has_item$#$#$#$#A:/$#$#$#$#head.txt
2019-02-27 12:54:53,128 - INFO: get key:has_item$#$#$#$#A:/$#$#$#$#HEAD.txt
[2019-02-27 12:54:53,239] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib64/python2.7/site-packages/flask_limiter/extension.py", line 544, in __inner
    return obj(*a, **k)
  File "/home/PyOne/app/front/views.py", line 117, in index
    ,endpoint='.index'))
  File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/PyOne/app/templates/theme/material/index.html", line 2, in top-level template code
    {% import 'theme/'+GetConfig('theme')+'/_macro.html' as macros %}
  File "/home/PyOne/app/templates/theme/material/layout.html", line 36, in top-level template code
    {%include 'theme/'+GetConfig('theme')+'/header.html'%}
  File "/home/PyOne/app/templates/theme/material/header.html", line 4, in top-level template code
    {%for user in get_od_user()%}
  File "/home/PyOne/app/utils/common.py", line 388, in get_od_user
    users=json.loads(redis_client.get(key))
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 10 column 58 (char 276)
[2019-02-27 12:54:53 +0000] [22219] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1748, in handle_exception
    return self.finalize_request(handler(e), from_error_handler=True)
  File "/home/PyOne/app/front/views.py", line 33, in page_not_found
    return render_template('theme/{}/500.html'.format(GetConfig('theme')),cur_user='',msg=msg), 500
  File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/PyOne/app/templates/theme/material/500.html", line 2, in top-level template code
    {% import 'theme/'+GetConfig('theme')+'/_macro.html' as macros %}
  File "/home/PyOne/app/templates/theme/material/layout.html", line 36, in top-level template code
    {%include 'theme/'+GetConfig('theme')+'/header.html'%}
  File "/home/PyOne/app/templates/theme/material/header.html", line 4, in top-level template code
    {%for user in get_od_user()%}
  File "/home/PyOne/app/utils/common.py", line 388, in get_od_user
    users=json.loads(redis_client.get(key))
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)

**Comment by sky-sunny** [comment]
已解决   原因 添加网盘时 key  多了 空格 去 配置文件删除 解决
