### ISSUE TITLE
获取文件列表时 中文路径被2次URL编码

### ISSUE THREAD

**Issue by 502647092** [abbeyokgo/PyOne#80]
上传文件报错
```
==> logs/PyOne.error.log <==
2019-05-03 21:51:50,084 - INFO: error to opreate _upload("/yumc/app/docker/pyone/PyOne/upload/HDTunePro_Win8_10.exe","/程序/HDTrue/HDTunePro_Win8_10.exe"), try times 4,error:Traceback (most recent call las
t):
  File "/yumc/app/docker/pyone/PyOne/app/utils/upload.py", line 27, in _upload
    AddResource(data,user)
  File "/yumc/app/docker/pyone/PyOne/app/utils/header.py", line 347, in AddResource
    item['size']=humanize.naturalsize(fdata.get('size'), gnu=True)
  File "/usr/lib/python2.7/site-packages/humanize/filesize.py", line 25, in naturalsize
    bytes = float(value)
TypeError: float() argument must be a string or a number

2019-05-03 21:51:50,085 - INFO: Traceback (most recent call last):
  File "/yumc/app/docker/pyone/PyOne/app/admin/manage.py", line 122, in read_status
    msg=_upload_session.next()['status']
StopIteration
```

**Comment by 502647092** [comment]
好像是文件没找到导致的
```
{u'error': {u'innerError': {u'date': u'2019-05-03T15:12:19', u'request-id': u'7da90d39-60c6-4f8b-ae68-2f96b0c0436e'}, u'message': u'Item does not exist', u'code': u'itemNotFound'}}
```

**Comment by 502647092** [comment]
我登录了OneDrive发现文件是存在的

**Comment by 502647092** [comment]
对比了多个路径
发现就这个路径下的文件不能被读取
![image](https://user-images.githubusercontent.com/10203793/57186630-66ba6a00-6f15-11e9-8c0e-fa3bf1ccadaf.png)

**Comment by 502647092** [comment]
我调试了一下程序 应该是中文被2次URL编码导致的
目录的名称是 `程序`
请求的参数是 `%25E7%25A8%258B%25E5%25BA%258F`

**Comment by 502647092** [comment]
我用 `PostMan` 调试了一下
用 `程序` 的单次URL编码 `%E7%A8%8B%E5%BA%8F` 可以请求到数据的
![image](https://user-images.githubusercontent.com/10203793/57188129-126eb480-6f2c-11e9-8e95-fb29d0d95d93.png)

**Comment by abbeyokgo** [comment]
好的，我确认一下
