### ISSUE TITLE
使用脚本上传文件RuntimeError: no suitable implementation for this system: IOError(10, 'No child processes')

### ISSUE THREAD

**Issue by ZaneCode6574** [abbeyokgo/PyOne#85]
在PyOne的离线下载里面可以直接实现下载上传，但是我的服务器用了AriaNg，下载完成以后调用PyOne的脚本就报错，但是单独执行可以上传

脚本
```
file=$3
if [ -d $file ];then
/usr/bin/python2.7 /www/wwwroot/我的网址/function.py UploadDir "$3" / A
echo "$3" >> /root/output.txt
else
/usr/bin/python2.7 /www/wwwroot/我的网址/function.py Upload "$3" / A
echo "$3" >> /root/output.txt
fi
```

在Aria2的配置里面加上了下载完成执行这个sh文件上传，输出发现报错
```
file=$3
+ file=/root/Download/QQMusicMac_Mgr.dmg
if [ -d $file ];then
/usr/bin/python2.7 /www/wwwroot/我的网址/function.py UploadDir "$3" / A
echo "$3" >> /root/output.txt
else
/usr/bin/python2.7 /www/wwwroot/我的网址/function.py Upload "$3" / A
echo "$3" >> /root/output.txt
fi
+ '[' -d /root/Download/QQMusicMac_Mgr.dmg ']'
+ /usr/bin/python2.7 /www/wwwroot/我的网址/function.py Upload /root/Download/QQMusicMac_Mgr.dmg / A
Traceback (most recent call last):
  File "/www/wwwroot/我的网址/function.py", line 3, in <module>
    from app.utils import *
  File "/www/wwwroot/我的网址/app/utils/__init__.py", line 2, in <module>
    from file_os import *
  File "/www/wwwroot/我的网址/app/utils/file_os.py", line 2, in <module>
    from header import *
  File "/www/wwwroot/我的网址/app/utils/header.py", line 27, in <module>
    from pymongo import uri_parser,MongoClient,ASCENDING,DESCENDING
  File "/usr/lib64/python2.7/site-packages/pymongo/__init__.py", line 77, in <module>
    from pymongo.collection import ReturnDocument
  File "/usr/lib64/python2.7/site-packages/pymongo/collection.py", line 32, in <module>
    from pymongo.bulk import BulkOperationBuilder, _Bulk
  File "/usr/lib64/python2.7/site-packages/pymongo/bulk.py", line 26, in <module>
    from pymongo.client_session import _validate_session_write_concern
  File "/usr/lib64/python2.7/site-packages/pymongo/client_session.py", line 93, in <module>
    from pymongo import monotonic, __version__
  File "/usr/lib64/python2.7/site-packages/pymongo/monotonic.py", line 31, in <module>
    from monotonic import monotonic as time
  File "/usr/lib/python2.7/site-packages/monotonic.py", line 169, in <module>
    raise RuntimeError('no suitable implementation for this system: ' + repr(e))
RuntimeError: no suitable implementation for this system: IOError(10, 'No child processes')
+ echo /root/Download/QQMusicMac_Mgr.dmg
/root/Download/QQMusicMac_Mgr.dmg
```

这是一个测试用的文件，如果我直接输入命令是可以上传的

希望dalao指点

**Comment by abbeyokgo** [comment]
无解。
