### ISSUE TITLE
ImportError: No module named self_config

### ISSUE THREAD

**Issue by DiseR-LawnX** [abbeyokgo/PyOne#90]
请问如何解决
[2019-05-27 00:43:33 +0000] [11034] [INFO] Starting gunicorn 19.9.0
[2019-05-27 00:43:33 +0000] [11034] [INFO] Listening at: http://0.0.0.0:34567 (11034)
[2019-05-27 00:43:33 +0000] [11034] [INFO] Using worker: eventlet
[2019-05-27 00:43:33 +0000] [11043] [INFO] Booting worker with pid: 11043
[2019-05-27 00:43:33 +0000] [11043] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/geventlet.py", line 102, in init_process
    super(EventletWorker, self).init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/www/wwwroot/PyOne/run.py", line 6, in <module>
    from app import create_app
  File "/www/wwwroot/PyOne/app/__init__.py", line 4, in <module>
    from config import config
  File "/www/wwwroot/PyOne/config.py", line 2, in <module>
    from self_config import *
ImportError: No module named self_config
[2019-05-27 00:43:33 +0000] [11043] [INFO] Worker exiting (pid: 11043)
[2019-05-27 00:43:33 +0000] [11034] [INFO] Shutting down: Master
[2019-05-27 00:43:33 +0000] [11034] [INFO] Reason: Worker failed to boot.

**Comment by whka** [comment]
时不时会出现这个问题
